name: testing-api
on: [push]
jobs:
  apiTest:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          #pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          
          uvicorn main:app
