name: testing-api
on: 
  push:
    branches:
      - workflow-test
jobs:
  apiTest:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install --upgrade pip setuptools wheel
          pip install -Iv fastai==1.0.59
          pip install -r requirements.txt
          
          uvicorn main:app


 # uses: s-weigand/setup-conda@v1
 #        with:
 #          update-conda: true
 #          python-version: 3.7

     # steps:
    #   - uses: actions/checkout@v2
    #   - name: Set up Python 3.7
    #     uses: s-weigand/setup-conda@v1
    #     with:
    #       update-conda: true
    #       python-version: 3.7
    #   - run: conda --version
    #   - run: which python

      #     - name: Conda setup
      #   uses: s-weigand/setup-conda@v1.0.3
      #   with:
      #     update-conda: true
      #     python-version: 3.7
      # # env activation as suggested by @s-weigand
      # - name: Conda environment creation
      #   run: |
      #     conda env create -f environment.yml
      #     source activate fastai
      #     # pip install -e .
